(in-package :cl-cli)

(defun %completion-zsh-command-labels (command)
  (format nil "~{~A~^|~}"
          (%completion-command-names command)))

(defun %completion-zsh-write-case-section (stream word body)
  (when (plusp (length body))
    (format stream "    case \"$~A\" in~%" word)
    (write-string body stream)
    (format stream "    esac~%")))

(defun %completion-zsh-render-value-cases (options stream)
  (dolist (section (list (list "previous_word"
                               (%completion-zsh-value-case-body options))
                         (list "current_word"
                               (%completion-zsh-attached-value-case-body options))))
    (%completion-zsh-write-case-section stream (first section) (second section))))

(defun %completion-zsh-command-case-source (app command)
  (with-output-to-string (out)
    (let ((command-options (append (app-global-options app)
                                   (command-options command))))
      (format out "    ~A)~%"
              (%completion-zsh-command-labels command))
      (write-string (%completion-zsh-option-specs-source command-options
                                                        "command_option_specs"
                                                        :app app)
                    out)
      (%completion-zsh-render-value-cases command-options out)
      (format out "      if [[ -z \"$current_word\" || \"$current_word\" == -* ]]; then~%")
      (format out "        _describe 'options' command_option_specs~%")
      (format out "        return 0~%")
      (format out "      fi~%")
      (format out "      return 0~%")
      (format out "      ;;~%"))))

(defun render-zsh-completion (app &optional stream)
  "Render a zsh completion script."
  (let ((stream (or stream *standard-output*))
        (function-name (%completion-function-name app))
        (app-name (app-name app)))
    (format stream "#compdef ~A~%" app-name)
    (format stream "~A() {~%" function-name)
    (format stream "  local current_word previous_word command_word~%")
    (format stream "  local -a command_specs option_specs command_option_specs value_candidates~%")
    (format stream "  current_word=${words[CURRENT]}~%")
    (format stream "  if (( CURRENT > 1 )); then~%")
    (format stream "    previous_word=${words[CURRENT-1]}~%")
    (format stream "  else~%")
    (format stream "    previous_word=~%")
    (format stream "  fi~%")
    (format stream "  if (( CURRENT > 2 )); then~%")
    (format stream "    command_word=${words[2]}~%")
    (format stream "  else~%")
    (format stream "    command_word=~%")
    (format stream "  fi~%")
    (write-string (%completion-zsh-command-specs-source app) stream)
    (write-string (%completion-zsh-option-specs-source (app-global-options app)
                                                       "option_specs"
                                                       :app app)
                  stream)
    (%completion-zsh-render-value-cases (app-global-options app) stream)
    (if (%completion-visible-commands app)
        (progn
          (format stream "  case \"$command_word\" in~%")
          (dolist (command (%completion-visible-commands app))
            (write-string (%completion-zsh-command-case-source app command)
                          stream))
          (format stream "    *)~%")
          (format stream "      if [[ \"$current_word\" == -* ]]; then~%")
          (format stream "        _describe 'options' option_specs~%")
          (format stream "        return 0~%")
          (format stream "      fi~%")
          (format stream "      _describe 'commands' command_specs~%")
          (format stream "      return 0~%")
          (format stream "      ;;~%")
          (format stream "  esac~%"))
        (progn
          (format stream "  if [[ -z \"$current_word\" || \"$current_word\" == -* ]]; then~%")
          (format stream "    _describe 'options' option_specs~%")
          (format stream "    return 0~%")
          (format stream "  fi~%")))
    (format stream "}~%")
    (format stream "compdef ~A ~A~%" function-name app-name)
    (values)))
