(defpackage :cl-cli
  (:use :cl)
  (:export
   :make-app
   :make-command
   :make-option
   :make-positional
   :exclusive-group
   :required-exclusive-group
   :inclusive-group
   :make-help-command
   :make-version-command
   :make-completion-command
   :make-docs-command
   :make-complete-command
   :make-standard-commands
   :render-docs
   :render-complete-reply
   :parse-argv
   :run-app
   :render-completion
   :render-bash-completion
   :render-zsh-completion
   :render-fish-completion
   :render-powershell-completion
   :render-nushell-completion
   :render-elvish-completion
   :render-manpage
   :render-markdown
   :render-json
   :current-process-argv
   :default-runtime-markers
   :extract-application-argv
   :application-argv
   :strip-argv-separators
   :print-app-help
   :print-command-help
   :command-by-name
   :option-value
   :option-value-source
   :positional-value
   :invocation-app
   :invocation-command
   :invocation-command-path
   :invocation-action
   :invocation-argv0
   :invocation-raw-argv
   :invocation-global-options
   :invocation-command-options
   :invocation-positionals
   :invocation-option-sources
   :invocation-stdout
   :invocation-stderr
   :app-name
   :app-version
   :app-summary
   :app-description
   :app-global-options
   :app-positionals
   :app-commands
   :app-default-command
   :app-handler
   :app-examples
   :app-help-footer
   :app-see-also
   :app-authors
   :app-manual-date
   :app-allow-abbreviated-options
   :app-expand-response-files
   :app-allow-negative-numbers
   :app-require-command
   :app-auto-help
   :command-name
   :command-aliases
   :command-group
   :command-description
   :command-examples
   :command-options
   :command-positionals
   :command-handler
   :command-hidden-p
   :command-deprecated
   :command-help-footer
   :option-key
   :option-names
   :option-negated-names
   :option-kind
   :option-description
   :option-value-name
   :option-value-type
   :option-value-min
   :option-value-max
   :option-value-delimiter
   :option-value-count
   :option-value-hint
   :option-default
   :option-env-vars
   :option-choices
   :option-completion-candidates
   :option-complete
   :option-parser
   :option-required-p
   :option-required-if
   :option-required-unless
   :option-requires
   :option-requires-any-of
   :option-conflicts-with
   :option-multiple-p
   :option-consume-optional-value-p
   :option-stop-parsing-p
   :option-hidden-p
   :option-deprecated
   :option-help-group
   :cli-usage-error
   :cli-unknown-option
   :cli-unknown-command
   :cli-missing-option-value
   :cli-missing-dependent-option
   :cli-missing-any-of-options
   :cli-conflicting-options
   :cli-missing-positional
   :cli-invalid-option-value
   :cli-invalid-positional-value
   :cli-unexpected-argument
   :cli-invalid-specification
   :cli-error-message
   :cli-usage-error-app
   :cli-usage-error-command
   :cli-unknown-option-name
   :cli-unknown-command-name
   :cli-missing-option-value-name
   :cli-missing-dependent-option-name
   :cli-missing-dependent-option-dependency
   :cli-missing-any-of-options-name
   :cli-missing-any-of-options-alternatives
   :cli-conflicting-options-left-option
   :cli-conflicting-options-right-option
   :cli-missing-positional-name
   :cli-invalid-option-value-name
   :cli-invalid-option-value-value
   :cli-invalid-option-value-cause
   :cli-invalid-positional-value-name
   :cli-invalid-positional-value-value
   :cli-invalid-positional-value-cause
   :cli-unexpected-argument-name))
